version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: buzz
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app/server:rw,cached # backend code
      - ./src:/usr/src/app/src:rw,cached # frontend code
